services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/data
    restart: always

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "8080:8080"
    depends_on:
      - ollama
    volumes:
      - openwebui_data:/app/backend/data
    environment:
      OLLAMA_BASE_URL: http://ollama:11434
    restart: always

volumes:
  ollama_data:
  openwebui_data: